### ISSUE TITLE
max_allowed_packet limit exceeded

### ISSUE THREAD

**Issue by ironijunior** [swisscom/backman#52]
Our Backman instance has stopped doing backups of our applications due to below error:
```
ERROR 1153 (08S01) at line 96: Got a packet bigger than 'max_allowed_packet' bytes
```

Is it possible to add this parameter to the mysqldump command?

`mysqldump --max_allowed_packet=512M ...`

**Comment by JamesClonk** [comment]
@ironijunior You can already do that by setting additional backup options / parameters in the configuration, like this:
```json
...
	"services": {
		"my_mysql_db": {
			"backup_options": [ "--max_allowed_packet=512M" ]
		},
	}
...
```

With `backup_options` you can add any additional flags or parameters, etc. you want to the mysqldump call. :smiley: 

Note: It might be that it would need to be written as `[ "--max_allowed_packet", "512M" ]` instead of being combined, not sure on that.
