### ISSUE TITLE
Teams workflow notification URL not recognised 

### ISSUE THREAD

**Issue by faizan-syed** [swisscom/backman#89]
Hi @JamesClonk @denysvitali
As microsoft has announced [Retirement of Office 365 connectors within Microsoft Teams](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/). I am creating teams workflow to get [notification on teams channel when webhook request is received](https://support.microsoft.com/en-us/office/create-incoming-webhooks-with-workflows-for-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498) for the backup failure event. But I am getting this below error when I use the new webhook URL for teams workflow. I have backman 2.1 image deployed in cloud foundry (iAPC).
Can you please suggest.

```
03/09/2024, 17:54:59 [APP/PROC/WEB/0] OUT level=error msg="unable to send Teams notification: webhook URL does not match one of expected patterns; got: \"https://prod-05.switzerlandnorth.logic.azure.com:443/workflows/6********9271c59***3e9/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=KWy9_5AD4DF*********ZeEgrAKs\", patterns: ^https:\\/\\/(?:.*\\.webhook|outlook)\\.office(?:365)?\\.com"
```

**Comment by faizan-syed** [comment]
Hi @JamesClonk  @denysvitali 
Any update on this ? can we skip the webhook URL validation for teams  as we have such restriction from microsoft to use teams workflow.

**Comment by JamesClonk** [comment]
Hi @faizan-syed, 

I'm sorry but unfortunately currently don't have much free capacity to look into this issue. The teams notification feature wasn't from me originally, so I'm not super familiar with that code part, but I suspect that its using a library to send those teams notifications and that the library is old or outdated and doesn't yet understand the newer teams workflow URLs.

edit:
I've bumped the library its using to a newer version that should support workflows and release it into `2.3.0`. Could you maybe check if that works for you? It would be great if that has solved the issue. Otherwise somebody else might have to look into it, I always appreciate pull requests :)

**Comment by faizan-syed** [comment]
@JamesClonk ,
Thanks a lot for your help
I tested the backman with release 2.3.0 and it supports the MS teams workflows.

**Comment by faizan-syed** [comment]
MS teams workflows is working with release 2.3.0
